spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}



