version: "3.9"
services:

  logistica:
    container_name: msvc-logistica
    build:
      context: ./
      dockerfile: ./logistica/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./logistica/.env
    networks:
      - rederpfovipol
    #depends_on:
    #  - mysql8
    restart: always

networks:
  rederpfovipol:
    name: rederpfovipol